apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flutter_map_geojson
  annotations:
    github.com/project-slug: yourparkingspace/flutter_map_geojson
spec:
  type: service
  lifecycle: production
  owner: mobile
